aliases:
  - &working-directory ~/format-package
  - &default-setup
    working_directory: *working-directory
    docker:
      - image: 'circleci/node:14'
  - &default-steps
    - checkout
    - attach_workspace:
      at: *working-directory
version: 2
jobs:
  setup:
    <<: *default-setup
    steps:
      - checkout
      - restore-cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            # https://circleci.com/docs/2.0/caching/
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run: npx greenkeeper-lockfile@next greenkeeper-lockfile-upload
      - run: yarn install --no-progress --silent
      - save-cache:
          paths:
            - ./node_modules
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: *working-directory
          paths:
            - ./node_modules
            - ./yarn.lock
  update-lockfile:
    <<: *default-setup
    steps:
      - checkout
      - attach_workspace:
          at: *working-directory
      - run: 'npx greenkeeper-lockfile@next greenkeeper-lockfile-upload'
  format:
    <<: *default-setup
    steps:
      - checkout
      - attach_workspace:
          at: *working-directory
      - run: yarn format
  git-status:
    <<: *default-setup
    steps:
      - checkout
      - attach_workspace:
          at: *working-directory
      - run: git diff --name-status --exit-code
  type-check:
    <<: *default-setup
    steps:
      - checkout
      - attach_workspace:
          at: *working-directory
      - run: yarn type-check
  lint:
    <<: *default-setup
    steps:
      - checkout
      - attach_workspace:
          at: *working-directory
      - run: yarn lint
  test:
    <<: *default-setup
    steps:
      - checkout
      - attach_workspace:
          at: *working-directory
      - run: yarn test --coverage --runInBand --ci
      - run: yarn codecov
  build-and-run:
    <<: *default-setup
    steps:
      - checkout
      - attach_workspace:
          at: *working-directory
      - run: yarn build
      - run: ./build/cli/index.js package.json

workflows:
  version: 2
  static-analysis:
    jobs:
      - setup
      - update-lockfile:
          requires:
            - setup
      - format:
        requires:
          - setup
      - git-status:
        requires:
          - setup
          - update-lockfile
          - format
      - type-check:
        requires:
          - setup
      - lint:
        requires:
          - setup
  test:
    jobs:
      - setup
      - test:
        requires:
          - setup
  build:
    jobs:
      - setup
      - build-and-run:
          requires:
            - setup
            - update-lockfile
